# Generated by Django 4.2.6 on 2023-10-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='templepack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packname', models.CharField(default='', max_length=255)),
                ('packcontent', models.CharField(default='', max_length=255)),
                ('images', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
